### ISSUE TITLE
Is there a reason aws Glue Catalog is missing?

### ISSUE THREAD

**Issue by royby-cyberark** [opendatadiscovery/awesome-data-catalogs#1]
Hi! Thanks for this awesome repo. 
I was wondering why aws Glue Catalog is missing. is there a specific reason (maybe its missing some critical capability that prevents it from being included?), or perhaps it was simply overlooked? 

Thanks!

**Comment by royby-cyberark** [comment]
I'm trying to understand if i'm missing something important regarding aws Glue.

**Comment by germanosin** [comment]
Hi, @royby-cyberark . Thanks for creating this issue. AWS Glue catalog doesn't provide search and discovery capabilities. It is the main focus to provide metadata to third-party tools like Athena or Spark. In this list we mostly focused on data discovery and observability tools

**Comment by royby-cyberark** [comment]
@germanosin thank you for the quick reply. make sense.

**Comment by germanosin** [comment]
You are more than welcome)
